export const notifications = [
    { id: 1, read: false, title: 'Policy expiring soon', time: '2w', body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'},
    { id: 2, read: false, title: 'Policy expiring soon', time: '1hr', body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'},
    { id: 3, read: false, title: 'Policy expired', time: '44m', body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'},
    { id: 4, read: false, title: 'Policy renewed', time: '1hr', body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'},
    { id: 5, read: true, title: 'Policy processing', time: '2w', body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'},
    { id: 6, read: false, title: 'Action required', time: '2w', body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'},
    { id: 7, read: true, title: 'Update your KYC', time: '2w', body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'},
    { id: 8, read: false, title: 'Notice', time: '2w', body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'},
    { id: 9, read: true, title: 'Claim processing', time: '2w', body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'},
    { id: 10, read: true, title: 'Settlement Disbursed', time: '2w', body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'},
]


export const news = [
    {
        id: 1, 
        title: 'Vestibulum aliquam', 
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum aliquam consectetur tempor', 
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum aliquam consectetur tempor. Sed vel euismod quam. Praesent elementum nibh sed porttitor cursus. Nam id magna lectus. Fusce tempor ligula et lacus venenatis posuere. Vivamus at ex nec nibh ultrices pulvinar eget rhoncus dolor. Nam orci purus, luctus sit amet pretium nec, condimentum ullamcorper diam. Fusce sed ex justo. Pellentesque consectetur sagittis ex eu interdum. Maecenas dictum maximus tempor. In viverra neque non libero hendrerit, ut accumsan libero condimentum. Maecenas at blandit nisi, ac rutrum odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        featuredImage: require('./assets/home1.jpg'),
        createdAt: '12-08-2020',
        publishedAt: '12-08-2020',
    },
    {
        id: 2, 
        title: 'Vestibulum aliquam', 
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum aliquam consectetur tempor', 
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum aliquam consectetur tempor. Sed vel euismod quam. Praesent elementum nibh sed porttitor cursus. Nam id magna lectus. Fusce tempor ligula et lacus venenatis posuere. Vivamus at ex nec nibh ultrices pulvinar eget rhoncus dolor. Nam orci purus, luctus sit amet pretium nec, condimentum ullamcorper diam. Fusce sed ex justo. Pellentesque consectetur sagittis ex eu interdum. Maecenas dictum maximus tempor. In viverra neque non libero hendrerit, ut accumsan libero condimentum. Maecenas at blandit nisi, ac rutrum odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        featuredImage: require('./assets/home2.jpg'),
        createdAt: '12-08-2020',
        publishedAt: '12-08-2020',
    },
    {
        id: 3, 
        title: 'Vestibulum aliquam', 
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum aliquam consectetur tempor', 
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum aliquam consectetur tempor. Sed vel euismod quam. Praesent elementum nibh sed porttitor cursus. Nam id magna lectus. Fusce tempor ligula et lacus venenatis posuere. Vivamus at ex nec nibh ultrices pulvinar eget rhoncus dolor. Nam orci purus, luctus sit amet pretium nec, condimentum ullamcorper diam. Fusce sed ex justo. Pellentesque consectetur sagittis ex eu interdum. Maecenas dictum maximus tempor. In viverra neque non libero hendrerit, ut accumsan libero condimentum. Maecenas at blandit nisi, ac rutrum odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        featuredImage: require('./assets/home3.jpg'),
        createdAt: '12-08-2020',
        publishedAt: '12-08-2020',
    },
    {
        id: 4, 
        title: 'Vestibulum aliquam', 
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum aliquam consectetur tempor', 
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum aliquam consectetur tempor. Sed vel euismod quam. Praesent elementum nibh sed porttitor cursus. Nam id magna lectus. Fusce tempor ligula et lacus venenatis posuere. Vivamus at ex nec nibh ultrices pulvinar eget rhoncus dolor. Nam orci purus, luctus sit amet pretium nec, condimentum ullamcorper diam. Fusce sed ex justo. Pellentesque consectetur sagittis ex eu interdum. Maecenas dictum maximus tempor. In viverra neque non libero hendrerit, ut accumsan libero condimentum. Maecenas at blandit nisi, ac rutrum odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        featuredImage: require('./assets/home1.jpg'),
        createdAt: '12-08-2020',
        publishedAt: '12-08-2020',
    },
    {
        id: 5, 
        title: 'Vestibulum aliquam', 
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum aliquam consectetur tempor', 
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum aliquam consectetur tempor. Sed vel euismod quam. Praesent elementum nibh sed porttitor cursus. Nam id magna lectus. Fusce tempor ligula et lacus venenatis posuere. Vivamus at ex nec nibh ultrices pulvinar eget rhoncus dolor. Nam orci purus, luctus sit amet pretium nec, condimentum ullamcorper diam. Fusce sed ex justo. Pellentesque consectetur sagittis ex eu interdum. Maecenas dictum maximus tempor. In viverra neque non libero hendrerit, ut accumsan libero condimentum. Maecenas at blandit nisi, ac rutrum odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        featuredImage: require('./assets/home2.jpg'),
        createdAt: '12-08-2020',
        publishedAt: '12-08-2020',
    },
    {
        id: 6, 
        title: 'Vestibulum aliquam', 
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum aliquam consectetur tempor', 
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum aliquam consectetur tempor. Sed vel euismod quam. Praesent elementum nibh sed porttitor cursus. Nam id magna lectus. Fusce tempor ligula et lacus venenatis posuere. Vivamus at ex nec nibh ultrices pulvinar eget rhoncus dolor. Nam orci purus, luctus sit amet pretium nec, condimentum ullamcorper diam. Fusce sed ex justo. Pellentesque consectetur sagittis ex eu interdum. Maecenas dictum maximus tempor. In viverra neque non libero hendrerit, ut accumsan libero condimentum. Maecenas at blandit nisi, ac rutrum odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        featuredImage: require('./assets/home3.jpg'),
        createdAt: '12-08-2020',
        publishedAt: '12-08-2020',
    },
]